typography_spectrum: 0.33769847685471177
color:
  brandColors:
    - '#04044a'
    - '#fce4ca'
    - '#f1644d'
    - '#7a3253'
    - '#796e58'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.33453043340705335
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2879280454944819
analytics:
  google: null
  facebook: null
  twitter: null
name: Trenchant
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: "1: Recording\_"
    id: a169577d-951d-43ce-819e-f7a697f89929
    type: content
favicon: null
title: Thoughts
purpose: []
