name: Trenchant
favicon: null
layout_spectrum: 0.2879280454944819
typography_spectrum: 0.33769847685471177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#04044a'
    - '#fce4ca'
    - '#f1644d'
    - '#7a3253'
    - '#796e58'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.33453043340705335
purpose: []
